"""create all tables from SQLAlchemy models

Revision ID: create_all_tables
Revises: 8d8b122b9742
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'create_all_tables'
down_revision: Union[str, None] = '8d8b122b9742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create all tables."""

    op.create_table('tenants',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('slug', sa.String(63), nullable=False, unique=True, comment='URL-safe identifier: acme-corp'),
        sa.Column('name', sa.String(255), nullable=False, comment='Business display name'),
        sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'LIMITED', 'SUSPENDED', 'TERMINATED', 'PURGED', name='tenantstatus'), nullable=False),
        sa.Column('plan_tier', sa.Enum('FREE', 'BASIC', 'STARTER', 'PRO', 'PRO_PLUS', 'PROFESSIONAL', 'ENTERPRISE', name='plantier'), nullable=False),
        sa.Column('plan_expires_at', sa.DateTime()),
        sa.Column('business_name', sa.String(255)),
        sa.Column('business_phone', sa.String(30), comment='E.164 format'),
        sa.Column('business_email', sa.String(255)),
        sa.Column('business_timezone', sa.String(50), nullable=False),
        sa.Column('business_address', sa.String()),
        sa.Column('business_website', sa.String(255)),
        sa.Column('industry', sa.String(100), comment="e.g. 'healthcare', 'legal', 'retail'"),
        sa.Column('ai_model', sa.Enum('LLAMA3_8B', 'LLAMA3_70B', 'MISTRAL_7B', 'MIXTRAL_8X7B', 'CUSTOM', 'RETELL_AI', name='aimodel'), nullable=False),
        sa.Column('ai_temperature', sa.Numeric(), nullable=False, comment='LLM temperature 0.0-2.0'),
        sa.Column('ai_max_tokens', sa.Integer(), nullable=False),
        sa.Column('ai_system_prompt', sa.String(), comment='Override default system prompt'),
        sa.Column('voice_type', sa.Enum('PIPER_DEFAULT', 'PIPER_MALE_1', 'PIPER_FEMALE_1', 'PIPER_CUSTOM', name='voicetype'), nullable=False),
        sa.Column('voice_speed', sa.Numeric(), nullable=False),
        sa.Column('stt_model', sa.Enum('WHISPER_LOCAL', 'WHISPER_API', 'DEEPGRAM', 'ASSEMBLY', 'RETELL_AI', name='transcriptsource'), nullable=False),
        sa.Column('stt_language', sa.String(10), nullable=False),
        sa.Column('max_call_duration', sa.Integer(), nullable=False, comment='seconds (10 min)'),
        sa.Column('voicemail_enabled', sa.Boolean(), nullable=False),
        sa.Column('voicemail_greeting', sa.String()),
        sa.Column('after_hours_action', sa.String(20), nullable=False),
        sa.Column('concurrent_calls_max', sa.Integer(), nullable=False),
        sa.Column('greeting_message', sa.String(), comment='First thing AI says'),
        sa.Column('hold_music_url', sa.String(500)),
        sa.Column('transfer_number', sa.String(30), comment='Fallback transfer number'),
        sa.Column('config_json', postgresql.JSONB(), nullable=False, server_default='{}'),
        sa.Column('features_json', postgresql.JSONB(), nullable=False, server_default='{}'),
        sa.Column('subdomain', sa.String(255), unique=True, comment='Unique subdomain for tenant portal'),
        sa.Column('owner_email', sa.String(255), comment='Tenant owner email'),
        sa.Column('locale', sa.String(10), nullable=False),
        sa.Column('current_period', sa.String(7), comment='Current billing period YYYY-MM'),
        sa.Column('metadata_json', postgresql.JSONB(), comment='Usage and billing metadata', server_default='{}'),
        sa.Column('deleted_at', sa.DateTime()),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.CheckConstraint('slug ~ \'^[a-z0-9-]+$\'', name='ck_tenants_slug_format'),
        sa.CheckConstraint('voice_speed BETWEEN 0.5 AND 2.0', name='ck_tenants_voice_speed_range'),
        sa.CheckConstraint('ai_temperature BETWEEN 0.0 AND 2.0', name='ck_tenants_temperature_range'),
        sa.UniqueConstraint('subdomain', name='uq_tenants_subdomain'),
        sa.UniqueConstraint('slug', name='uq_tenants_slug'),
    )

    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('email', sa.String(255), nullable=False, comment='Login email'),
        sa.Column('password_hash', sa.String(255), nullable=False, comment='bcrypt hash'),
        sa.Column('first_name', sa.String(100), nullable=False),
        sa.Column('last_name', sa.String(100), nullable=False),
        sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'AGENT', 'VIEWER', name='userrole'), nullable=False),
        sa.Column('phone', sa.String(30), comment='Direct dial for transfers'),
        sa.Column('avatar_url', sa.String(500)),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_login_at', sa.DateTime()),
        sa.Column('email_verified_at', sa.DateTime()),
        sa.Column('timezone', sa.String(50), nullable=False),
        sa.Column('notification_prefs', postgresql.JSONB(), nullable=False, comment='Per-user notification preferences'),
        sa.Column('api_key_hash', sa.String(255), comment='For service-to-service auth'),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('deleted_at', sa.DateTime(), comment='NULL = active, timestamp = soft-deleted'),
        sa.UniqueConstraint('tenant_id', 'email', name='uq_user_email_per_tenant'),
    )

    op.create_table('tenant_configs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, unique=True),
        sa.Column('ai_settings', postgresql.JSONB(), nullable=False, comment='AI behavior: voice_id, speech_rate, greeting, language, etc.'),
        sa.Column('routing_rules', postgresql.JSONB(), nullable=False, comment='Call routing: business_hours, after_hours_action, overflow'),
        sa.Column('notification_settings', postgresql.JSONB(), nullable=False, comment='Notification: email, sms, daily_summary, missed_call_alert'),
        sa.Column('integrations', postgresql.JSONB(), nullable=False, comment='Third-party integrations: calendar, CRM, etc.'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.UniqueConstraint('tenant_id', name='uq_tenant_configs_tenant_id'),
    )

    op.create_table('calls',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('call_sid', sa.String(64), nullable=False, unique=True, comment='FreeSWITCH call UUID'),
        sa.Column('parent_call_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id"), comment='For transferred calls'),
        sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='calldirection'), nullable=False),
        sa.Column('caller_number', sa.String(30), nullable=False, comment='E.164'),
        sa.Column('caller_name', sa.String(255), comment='CNAM if available'),
        sa.Column('caller_id_hash', sa.String(64), comment='SHA-256 for dedup'),
        sa.Column('destination_number', sa.String(30), nullable=False, comment='Called number (DID)'),
        sa.Column('status', sa.Enum('QUEUED', 'RINGING', 'ANSWERED', 'ACTIVE', 'ON_HOLD', 'TRANSFERRED', 'COMPLETED', 'FAILED', 'VOICEMAIL', 'NO_ANSWER', name='callstatus'), nullable=False),
        sa.Column('result', sa.Enum('SUCCESS', 'VOICEMAIL_LEFT', 'NO_ANSWER', 'BUSY', 'FAILED', 'TRANSFERRED', 'HANGUP', 'ERROR', name='callresult')),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('answered_at', sa.DateTime()),
        sa.Column('ended_at', sa.DateTime()),
        sa.Column('duration_seconds', sa.Integer(), comment='Total call duration in seconds'),
        sa.Column('talk_time_seconds', sa.Integer(), nullable=False, comment='Time after answer'),
        sa.Column('ai_handled', sa.Boolean(), nullable=False, comment='Was AI involved?'),
        sa.Column('ai_model_used', sa.Enum('LLAMA3_8B', 'LLAMA3_70B', 'MISTRAL_7B', 'MIXTRAL_8X7B', 'CUSTOM', 'RETELL_AI', name='aimodel')),
        sa.Column('transcript_summary', sa.String(), comment='LLM-generated summary'),
        sa.Column('sentiment_score', sa.Numeric(4, 3), comment='-1.0 to +1.0'),
        sa.Column('intent_detected', sa.String(100), comment='Primary intent'),
        sa.Column('transferred_to', sa.String(30), comment='Number transferred to'),
        sa.Column('transfer_reason', sa.String(255)),
        sa.Column('audio_quality_mos', sa.Numeric(3, 2), comment='Mean Opinion Score'),
        sa.Column('stt_confidence_avg', sa.Numeric(4, 3), comment='Average STT confidence'),
        sa.Column('llm_tokens_used', sa.Integer(), nullable=False),
        sa.Column('tts_chars_used', sa.Integer(), nullable=False),
        sa.Column('voicemail_left', sa.Boolean(), nullable=False),
        sa.Column('voicemail_duration', sa.Integer(), comment='seconds'),
        sa.Column('estimated_cost', sa.Numeric(10, 6), nullable=False),
        sa.Column('tags', postgresql.JSONB(), nullable=False, server_default='[]'),
        sa.Column('metadata_json', postgresql.JSONB(), nullable=False, server_default='{}'),
        sa.Column('partition_key', sa.String(7), comment='YYYY-MM for partition pruning'),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.UniqueConstraint('call_sid', name='uq_calls_call_sid'),
    )

    op.create_table('call_legs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('call_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id", ondelete='CASCADE'), nullable=False),
        sa.Column('leg_type', sa.String(20), nullable=False, comment='caller | ai_agent | human_agent | voicemail | conference'),
        sa.Column('leg_index', sa.Integer(), nullable=False, comment='Order of legs'),
        sa.Column('display_name', sa.String(255), comment="e.g. 'AI Agent', 'John Smith'"),
        sa.Column('phone_number', sa.String(30)),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), comment='If staff member'),
        sa.Column('sip_call_id', sa.String(128)),
        sa.Column('local_sdp', sa.String()),
        sa.Column('remote_sdp', sa.String()),
        sa.Column('rtp_local_ip', sa.String()),
        sa.Column('rtp_local_port', sa.Integer()),
        sa.Column('joined_at', sa.DateTime(), nullable=False),
        sa.Column('left_at', sa.DateTime()),
        sa.Column('duration_seconds', sa.Integer()),
        sa.Column('status', sa.String(20), nullable=False, comment='active | hold | muted | disconnected'),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
    )

    op.create_table('recordings',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('call_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id", ondelete='CASCADE'), nullable=False),
        sa.Column('call_leg_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("call_legs.id")),
        sa.Column('file_path', sa.String(500), nullable=False, comment='Relative path on storage'),
        sa.Column('file_size_bytes', sa.Integer(), nullable=False),
        sa.Column('file_format', sa.String(10), nullable=False, comment='wav | mp3 | ogg | webm'),
        sa.Column('duration_seconds', sa.Numeric(8, 2), nullable=False),
        sa.Column('sample_rate', sa.Integer(), nullable=False),
        sa.Column('channels', sa.Integer(), nullable=False),
        sa.Column('storage_backend', sa.String(20), nullable=False, comment='local | s3 | minio'),
        sa.Column('storage_bucket', sa.String(100)),
        sa.Column('storage_key', sa.String(500)),
        sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete'),
        sa.Column('deleted_at', sa.DateTime()),
        sa.Column('delete_after_days', sa.Integer(), comment='Auto-delete policy'),
        sa.Column('access_url', sa.String(1000), comment='Temporary signed URL'),
        sa.Column('access_expires_at', sa.DateTime()),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
    )

    op.create_table('conversations',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('call_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id", ondelete='CASCADE'), nullable=False, unique=True),
        sa.Column('turn_count', sa.Integer(), nullable=False, comment='Number of exchanges'),
        sa.Column('topic_category', sa.String(100), comment='Classified topic'),
        sa.Column('summary', sa.String(), comment='LLM-generated summary'),
        sa.Column('satisfaction_score', sa.Numeric(4, 3), comment='Estimated caller satisfaction'),
        sa.Column('resolved', sa.Boolean(), comment='Was the issue resolved?'),
        sa.Column('resolution_type', sa.String(50), comment="'answer_provided', 'appointment_booked', 'transferred', etc."),
        sa.Column('follow_up_required', sa.Boolean(), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.UniqueConstraint('call_id', name='uq_conversations_call_id'),
    )

    op.create_table('transcripts',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('call_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id", ondelete='CASCADE'), nullable=False),
        sa.Column('source', sa.Enum('WHISPER_LOCAL', 'WHISPER_API', 'DEEPGRAM', 'ASSEMBLY', 'RETELL_AI', name='transcriptsource'), nullable=False),
        sa.Column('model_version', sa.String(50), comment="e.g. 'whisper.cpp:v1.5.4'"),
        sa.Column('language', sa.String(10), nullable=False),
        sa.Column('segment_start', sa.Numeric(8, 3), nullable=False, comment='seconds from call start'),
        sa.Column('segment_end', sa.Numeric(8, 3), nullable=False),
        sa.Column('speaker', sa.String(20), nullable=False, comment='caller | agent | unknown'),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('text_normalized', sa.String(), comment='Lowercase, normalized'),
        sa.Column('confidence', sa.Numeric(4, 3), comment='0.000 to 1.000'),
        sa.Column('words_json', postgresql.JSONB(), comment='Per-word timestamps & confidence'),
        sa.Column('search_vector', postgresql.TSVECTOR(), comment='Updated via trigger'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.CheckConstraint('segment_end > segment_start', name='ck_transcripts_segment_timing'),
    )

    op.create_table('messages',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('conversation_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("conversations.id", ondelete='CASCADE'), nullable=False),
        sa.Column('call_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id", ondelete='CASCADE'), nullable=False),
        sa.Column('role', sa.Enum('SYSTEM', 'ASSISTANT', 'USER', 'TOOL', name='messagerole'), nullable=False),
        sa.Column('message_type', sa.Enum('TEXT', 'TOOL_CALL', 'TOOL_RESULT', 'TRANSFER', 'VOICEMAIL', 'HANGUP', name='messagetype'), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('content_json', postgresql.JSONB(), comment='Structured data for tool calls'),
        sa.Column('llm_model', sa.Enum('LLAMA3_8B', 'LLAMA3_70B', 'MISTRAL_7B', 'MIXTRAL_8X7B', 'CUSTOM', 'RETELL_AI', name='aimodel')),
        sa.Column('llm_temperature', sa.Numeric(3, 2)),
        sa.Column('tokens_prompt', sa.Integer(), nullable=False),
        sa.Column('tokens_completion', sa.Integer(), nullable=False),
        sa.Column('tokens_total', sa.Integer()),
        sa.Column('latency_ms', sa.Integer(), comment='Generation latency'),
        sa.Column('sequence_number', sa.Integer(), nullable=False, comment='Order in conversation'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
    )

    op.create_table('tool_calls',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('call_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id", ondelete='CASCADE'), nullable=False),
        sa.Column('message_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("messages.id"), comment='The message that triggered it'),
        sa.Column('tool_name', sa.String(100), nullable=False, comment="e.g. 'book_appointment'"),
        sa.Column('tool_version', sa.String(20), nullable=False),
        sa.Column('arguments_json', postgresql.JSONB(), nullable=False, comment='Parameters passed'),
        sa.Column('result_json', postgresql.JSONB(), comment='Result returned'),
        sa.Column('error_json', postgresql.JSONB(), comment='If failed'),
        sa.Column('status', sa.String(20), nullable=False, comment='pending | running | success | failed | timeout'),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime()),
        sa.Column('duration_ms', sa.Integer(), comment='Execution time'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
    )

    op.create_table('prompts',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('description', sa.String()),
        sa.Column('prompt_type', sa.String(30), nullable=False, comment='system | greeting | transfer | voicemail | closing | tool_call | custom'),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('variables_json', postgresql.JSONB(), nullable=False, comment='Variable names e.g. ["business_name", "hours"]', server_default='[]'),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, comment='Only one active per type per tenant'),
        sa.Column('use_count', sa.Integer(), nullable=False),
        sa.Column('avg_response_score', sa.Numeric(4, 3), comment='User rating (future)'),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.CheckConstraint('prompt_type IN (\'system\', \'greeting\', \'transfer\', \'voicemail\', \'closing\', \'tool_call\', \'custom\')', name='ck_prompts_prompt_type_valid'),
    )

    op.create_table('appointments',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('call_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id"), comment='May be booked via call'),
        sa.Column('caller_number', sa.String(30), nullable=False),
        sa.Column('caller_name', sa.String(255)),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('description', sa.String()),
        sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='appointmentstatus'), nullable=False),
        sa.Column('scheduled_date', sa.Date(), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=False),
        sa.Column('end_time', sa.Time(), nullable=False),
        sa.Column('timezone', sa.String(50), nullable=False),
        sa.Column('appointment_type', sa.String(50), nullable=False, comment='in_person | phone | video | virtual'),
        sa.Column('location', sa.String(500)),
        sa.Column('staff_user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), comment='Assigned staff'),
        sa.Column('staff_name', sa.String(255), comment='Denormalized for display'),
        sa.Column('confirmed_at', sa.DateTime()),
        sa.Column('confirmed_by', sa.String(20), comment='ai | staff | caller | system'),
        sa.Column('reminder_sent_at', sa.DateTime()),
        sa.Column('cancelled_at', sa.DateTime()),
        sa.Column('cancellation_reason', sa.String()),
        sa.Column('external_id', sa.String(255), comment='Google/Outlook event ID'),
        sa.Column('external_provider', sa.Enum('GOOGLE_CALENDAR', 'OUTLOOK_CALENDAR', 'ZAPIER', 'MAKE', 'HUBSPOT', 'SALESFORCE', 'SLACK', 'TEAMS', name='integrationprovider')),
        sa.Column('sync_status', sa.String(20), nullable=False, comment='pending | synced | failed | conflict'),
        sa.Column('sync_error', sa.String()),
        sa.Column('metadata_json', postgresql.JSONB(), nullable=False, server_default='{}'),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.CheckConstraint('end_time > start_time', name='ck_appointments_time_order'),
    )

    op.create_table('routing_rules',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.String()),
        sa.Column('priority', sa.Integer(), nullable=False, comment='Lower = higher priority'),
        sa.Column('rule_type', sa.Enum('AUTO_ATTENDANT', 'TIME_BASED', 'INTENT_BASED', 'CALLER_ID', 'DEFAULT', name='routingtype'), nullable=False),
        sa.Column('conditions_json', postgresql.JSONB(), nullable=False, comment='JSON conditions for rule matching', server_default='{}'),
        sa.Column('action', sa.Enum('ANSWER', 'TRANSFER', 'VOICEMAIL', 'REJECT', 'QUEUE', 'MENU', name='routingaction'), nullable=False),
        sa.Column('action_config_json', postgresql.JSONB(), nullable=False, comment='JSON parameters for the action', server_default='{}'),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('effective_from', sa.DateTime(), nullable=False),
        sa.Column('effective_to', sa.DateTime()),
        sa.Column('match_count', sa.Integer(), nullable=False, comment='Times this rule matched'),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.UniqueConstraint('tenant_id', 'priority', name='uq_rule_priority'),
    )

    op.create_table('faq_entries',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('question', sa.String(), nullable=False),
        sa.Column('answer', sa.String(), nullable=False),
        sa.Column('category', sa.String(100), nullable=False),
        sa.Column('tags_json', postgresql.JSONB(), nullable=False, server_default='[]'),
        sa.Column('question_variants_json', postgresql.JSONB(), nullable=False, comment='["alternate phrasing 1", ...]', server_default='[]'),
        sa.Column('embeddings_json', postgresql.JSONB(), comment='Vector embeddings (future)'),
        sa.Column('search_vector', postgresql.TSVECTOR(), comment='Updated via trigger'),
        sa.Column('use_count', sa.Integer(), nullable=False, comment='Times used by AI'),
        sa.Column('helpful_count', sa.Integer(), nullable=False, comment='Caller marked helpful'),
        sa.Column('last_used_at', sa.DateTime()),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('deleted_at', sa.DateTime(), comment='NULL = active, timestamp = soft-deleted'),
    )

    op.create_table('business_hours',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('day_of_week', sa.String(10), nullable=False, comment='monday | tuesday | ... | sunday'),
        sa.Column('open_time', sa.Time(), nullable=False),
        sa.Column('close_time', sa.Time(), nullable=False),
        sa.Column('is_closed', sa.Boolean(), nullable=False, comment='Closed all day'),
        sa.Column('timezone', sa.String(50), nullable=False),
        sa.Column('effective_from', sa.Date(), nullable=False),
        sa.Column('effective_to', sa.Date(), comment='NULL = ongoing'),
        sa.Column('is_override', sa.Boolean(), nullable=False, comment='True for holiday/special hours'),
        sa.Column('override_name', sa.String(100), comment="e.g. 'Christmas Day'"),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
    )

    op.create_table('holiday_schedules',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('name', sa.String(255), nullable=False, comment="e.g. 'Christmas Day'"),
        sa.Column('is_closed', sa.Boolean(), nullable=False, comment='Closed all day'),
        sa.Column('open_time', sa.Time(), comment='NULL if closed all day'),
        sa.Column('close_time', sa.Time(), comment='NULL if closed all day'),
        sa.Column('timezone', sa.String(50), nullable=False),
        sa.Column('is_recurring', sa.Boolean(), nullable=False, comment='Repeats annually on same month/day'),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
    )

    op.create_table('caller_profiles',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('phone_number', sa.String(30), nullable=False, comment='E.164'),
        sa.Column('phone_hash', sa.String(64), nullable=False, comment='SHA-256 normalized number'),
        sa.Column('name', sa.String(255)),
        sa.Column('email', sa.String(255)),
        sa.Column('company', sa.String(255)),
        sa.Column('notes', sa.String()),
        sa.Column('tags_json', postgresql.JSONB(), nullable=False, server_default='[]'),
        sa.Column('summary', sa.String(), comment='LLM summary of interactions'),
        sa.Column('preferred_language', sa.String(10), nullable=False),
        sa.Column('total_calls', sa.Integer(), nullable=False),
        sa.Column('total_duration_sec', sa.Integer(), nullable=False),
        sa.Column('last_call_at', sa.DateTime()),
        sa.Column('priority', sa.String(20), nullable=False, comment='blocked | low | normal | high | vip'),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.CheckConstraint('priority IN (\'blocked\', \'low\', \'normal\', \'high\', \'vip\')', name='ck_caller_profiles_priority_range'),
        sa.UniqueConstraint('tenant_id', 'phone_hash', name='uq_caller_per_tenant'),
    )

    op.create_table('call_summaries',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('call_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id", ondelete='CASCADE'), nullable=False, unique=True),
        sa.Column('summary', sa.String(), comment='Natural language summary'),
        sa.Column('sentiment', sa.String(20), comment='positive | neutral | negative'),
        sa.Column('sentiment_score', sa.Numeric(4, 3), comment='-1.0 to +1.0'),
        sa.Column('key_points_json', postgresql.JSONB(), comment='Extracted key discussion points'),
        sa.Column('action_items_json', postgresql.JSONB(), comment='Follow-up action items'),
        sa.Column('primary_intent', sa.String(100)),
        sa.Column('intents_detected_json', postgresql.JSONB()),
        sa.Column('call_quality_score', sa.Integer(), comment='1-10 subjective quality'),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.UniqueConstraint('call_id', name='uq_call_summaries_call_id'),
    )

    op.create_table('notification_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'WEBHOOK', 'SLACK', 'PUSH', 'IN_APP', name='notificationchannel'), nullable=False),
        sa.Column('recipient', sa.String(255), nullable=False, comment='Email, phone, URL, or channel ID'),
        sa.Column('subject', sa.String(500)),
        sa.Column('content', sa.String()),
        sa.Column('content_html', sa.String()),
        sa.Column('event_type', sa.String(100), comment='call.completed | voicemail.received | etc.'),
        sa.Column('entity_type', sa.String(50), comment='call | appointment | etc.'),
        sa.Column('entity_id', postgresql.UUID(as_uuid=True)),
        sa.Column('status', sa.String(20), nullable=False, comment='pending | sent | delivered | failed | bounced'),
        sa.Column('error_message', sa.String()),
        sa.Column('delivered_at', sa.DateTime()),
        sa.Column('provider_message_id', sa.String(255), comment='External message ID'),
        sa.Column('metadata_json', postgresql.JSONB(), nullable=False, server_default='{}'),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
    )

    op.create_table('integration_connections',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('provider', sa.Enum('GOOGLE_CALENDAR', 'OUTLOOK_CALENDAR', 'ZAPIER', 'MAKE', 'HUBSPOT', 'SALESFORCE', 'SLACK', 'TEAMS', name='integrationprovider'), nullable=False),
        sa.Column('connection_name', sa.String(255), nullable=False),
        sa.Column('config_json', postgresql.JSONB(), nullable=False, comment='Provider-specific settings', server_default='{}'),
        sa.Column('auto_sync', sa.Boolean(), nullable=False),
        sa.Column('sync_frequency_min', sa.Integer(), nullable=False, comment='Minutes between syncs'),
        sa.Column('status', sa.String(20), nullable=False, comment='pending | connected | error | disconnected'),
        sa.Column('last_sync_at', sa.DateTime()),
        sa.Column('error_message', sa.String()),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.UniqueConstraint('tenant_id', 'provider', name='uq_integration_per_tenant'),
    )

    op.create_table('oauth_tokens',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('provider', sa.Enum('GOOGLE_CALENDAR', 'OUTLOOK_CALENDAR', 'ZAPIER', 'MAKE', 'HUBSPOT', 'SALESFORCE', 'SLACK', 'TEAMS', name='integrationprovider'), nullable=False),
        sa.Column('provider_account_id', sa.String(255), comment='User ID at provider'),
        sa.Column('access_token_enc', sa.String(), nullable=False, comment='AES-256-GCM encrypted'),
        sa.Column('refresh_token_enc', sa.String(), comment='AES-256-GCM encrypted'),
        sa.Column('token_type', sa.String(20), nullable=False),
        sa.Column('scopes_json', postgresql.JSONB(), nullable=False, server_default='[]'),
        sa.Column('expires_at', sa.DateTime()),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('last_used_at', sa.DateTime()),
        sa.Column('refresh_count', sa.Integer(), nullable=False),
        sa.Column('last_refresh_at', sa.DateTime()),
        sa.Column('refresh_error', sa.String()),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
    )

    op.create_table('webhook_endpoints',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('url', sa.String(500), nullable=False, comment='Webhook URL'),
        sa.Column('description', sa.String(255)),
        sa.Column('events_json', postgresql.JSONB(), nullable=False, comment='["call.started", "call.ended", ...]'),
        sa.Column('secret', sa.String(255), comment='HMAC-SHA256 secret'),
        sa.Column('headers_json', postgresql.JSONB(), nullable=False, comment='Custom HTTP headers', server_default='{}'),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('success_count', sa.Integer(), nullable=False),
        sa.Column('failure_count', sa.Integer(), nullable=False),
        sa.Column('last_success_at', sa.DateTime()),
        sa.Column('last_failure_at', sa.DateTime()),
        sa.Column('last_error', sa.String()),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
    )

    op.create_table('sync_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('provider', sa.Enum('GOOGLE_CALENDAR', 'OUTLOOK_CALENDAR', 'ZAPIER', 'MAKE', 'HUBSPOT', 'SALESFORCE', 'SLACK', 'TEAMS', name='integrationprovider'), nullable=False),
        sa.Column('operation', sa.String(100), nullable=False, comment="e.g. 'sync_calendar'"),
        sa.Column('direction', sa.String(10), nullable=False, comment='inbound | outbound | bidirectional'),
        sa.Column('status', sa.String(20), nullable=False, comment='started | success | partial | failed'),
        sa.Column('records_processed', sa.Integer(), nullable=False),
        sa.Column('records_created', sa.Integer(), nullable=False),
        sa.Column('records_updated', sa.Integer(), nullable=False),
        sa.Column('records_failed', sa.Integer(), nullable=False),
        sa.Column('error_message', sa.String()),
        sa.Column('details_json', postgresql.JSONB(), nullable=False, comment='Additional context', server_default='{}'),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime()),
        sa.Column('duration_ms', sa.Integer(), comment='Execution time'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
    )

    op.create_table('usage_records',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('event_type', sa.String(50), nullable=False, comment="'call', 'stt', 'tts', 'llm', 'storage'"),
        sa.Column('event_subtype', sa.String(50), comment="'inbound', 'outbound', 'whisper', 'piper'"),
        sa.Column('call_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("calls.id")),
        sa.Column('resource_id', postgresql.UUID(as_uuid=True), comment='Generic reference'),
        sa.Column('quantity', sa.Numeric(12, 4), nullable=False, comment='Amount consumed (minutes, tokens, MB)'),
        sa.Column('unit', sa.String(20), nullable=False, comment="'minutes', 'tokens', 'seconds', 'mb'"),
        sa.Column('cost_per_unit', sa.Numeric(12, 8), nullable=False),
        sa.Column('total_cost', sa.Numeric(12, 6), nullable=False),
        sa.Column('period_hour', sa.DateTime(), nullable=False, comment='Truncated to hour'),
        sa.Column('period_day', sa.Date(), nullable=False),
        sa.Column('period_month', sa.String(7), nullable=False, comment='YYYY-MM'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
    )

    op.create_table('audit_logs',
        sa.Column('id', sa.BigInteger(), primary_key=True, nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'API_KEY', 'AI_AGENT', 'INTEGRATION', name='actortype'), nullable=False),
        sa.Column('actor_id', postgresql.UUID(as_uuid=True)),
        sa.Column('actor_email', sa.String(255)),
        sa.Column('action', sa.String(100), nullable=False, comment="e.g. 'call.answer', 'user.login', 'setting.update'"),
        sa.Column('resource_type', sa.String(50), nullable=False, comment="e.g. 'call', 'user'"),
        sa.Column('resource_id', postgresql.UUID(as_uuid=True)),
        sa.Column('details_json', postgresql.JSONB(), nullable=False, comment='Before/after values', server_default='{}'),
        sa.Column('ip_address', postgresql.INET()),
        sa.Column('user_agent', sa.String(500)),
        sa.Column('severity', sa.String(10), nullable=False, comment='debug | info | warning | error | critical'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
    )

    op.create_table('plan_definitions',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('plan_tier', sa.Enum('FREE', 'BASIC', 'STARTER', 'PRO', 'PRO_PLUS', 'PROFESSIONAL', 'ENTERPRISE', name='plantier'), nullable=False, unique=True),
        sa.Column('display_name', sa.String(100), nullable=False),
        sa.Column('description', sa.String()),
        sa.Column('max_minutes_monthly', sa.Integer(), nullable=False),
        sa.Column('max_concurrent_calls', sa.Integer(), nullable=False),
        sa.Column('max_users', sa.Integer(), nullable=False),
        sa.Column('max_phone_numbers', sa.Integer(), nullable=False),
        sa.Column('features_json', postgresql.JSONB(), nullable=False, comment='Feature flags map: {feature_name: true/false}', server_default='{}'),
        sa.Column('is_public', sa.Boolean(), nullable=False, comment='Shown on pricing page'),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp (UTC)', server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record last-update timestamp (UTC)', server_default=sa.text('now()')),
        sa.UniqueConstraint('plan_tier', name='uq_plan_definitions_plan_tier'),
    )

    op.create_table('prompt_versions',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('prompt_type', sa.String(30), nullable=False, comment='system | greeting | hold | voicemail | transfer | goodbye | fallback | custom_*'),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(150), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('variables_json', postgresql.JSONB(), nullable=False, server_default='{}'),
        sa.Column('status', sa.String(20), nullable=False, comment='draft | active | archived | ab_test'),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('ab_test_group', sa.String(1), comment="'A' or 'B' when in a test"),
        sa.Column('ab_test_id', postgresql.UUID(as_uuid=True)),
        sa.Column('times_used', sa.Integer(), nullable=False),
        sa.Column('avg_call_rating', sa.Numeric(4, 3)),
        sa.Column('created_by', postgresql.UUID(as_uuid=True)),
        sa.Column('notes', sa.String()),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('activated_at', sa.DateTime()),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
    )

    op.create_table('prompt_ab_tests',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('name', sa.String(150), nullable=False),
        sa.Column('description', sa.String()),
        sa.Column('prompt_type', sa.String(30), nullable=False),
        sa.Column('variant_a_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('variant_b_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('split_percentage', sa.Integer(), nullable=False, comment='Percent of traffic routed to variant B'),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('ended_at', sa.DateTime()),
        sa.Column('winning_variant', sa.String(1)),
        sa.Column('total_participants', sa.Integer(), nullable=False),
        sa.Column('variant_a_calls', sa.Integer(), nullable=False),
        sa.Column('variant_b_calls', sa.Integer(), nullable=False),
        sa.Column('variant_a_avg_rating', sa.Numeric(4, 3)),
        sa.Column('variant_b_avg_rating', sa.Numeric(4, 3)),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
    )

    op.create_table('onboarding_pipelines',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('tenant_name', sa.String(150), nullable=False),
        sa.Column('tenant_email', sa.String(255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
    )

    op.create_table('onboarding_steps',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('pipeline_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("onboarding_pipelines.id", ondelete='CASCADE'), nullable=False),
        sa.Column('step_id', sa.String(50), nullable=False),
        sa.Column('name', sa.String(150), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('step_order', sa.Integer(), nullable=False),
        sa.Column('auto_completes', sa.Boolean(), nullable=False),
        sa.Column('requires_action', sa.Boolean(), nullable=False),
        sa.Column('estimated_days', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, comment='pending | in_progress | completed | blocked | skipped'),
        sa.Column('completed_at', sa.DateTime()),
        sa.Column('notes', sa.String()),
        sa.Column('assignee', sa.String(150)),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
    )

    op.create_table('onboarding_emails',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column('pipeline_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("onboarding_pipelines.id", ondelete='CASCADE')),
        sa.Column('email_id', sa.String(120), nullable=False),
        sa.Column('trigger_step', sa.String(50), nullable=False),
        sa.Column('subject', sa.String(500), nullable=False),
        sa.Column('template', sa.String(80), nullable=False),
        sa.Column('delay_hours', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, comment='pending | sent | delivered | opened | failed | skipped'),
        sa.Column('sent_at', sa.DateTime()),
        sa.Column('delivered_at', sa.DateTime()),
        sa.Column('opened_at', sa.DateTime()),
        sa.Column('error', sa.String()),
        sa.Column('tenant_id', postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id", ondelete='CASCADE'), nullable=False, comment='FK to tenants.id — row-level tenant isolation'),
    )


def downgrade() -> None:
    """Drop all tables."""
    op.drop_table('onboarding_emails')
    op.drop_table('onboarding_steps')
    op.drop_table('onboarding_pipelines')
    op.drop_table('prompt_ab_tests')
    op.drop_table('prompt_versions')
    op.drop_table('plan_definitions')
    op.drop_table('audit_logs')
    op.drop_table('usage_records')
    op.drop_table('sync_logs')
    op.drop_table('webhook_endpoints')
    op.drop_table('oauth_tokens')
    op.drop_table('integration_connections')
    op.drop_table('notification_logs')
    op.drop_table('call_summaries')
    op.drop_table('caller_profiles')
    op.drop_table('holiday_schedules')
    op.drop_table('business_hours')
    op.drop_table('faq_entries')
    op.drop_table('routing_rules')
    op.drop_table('appointments')
    op.drop_table('prompts')
    op.drop_table('tool_calls')
    op.drop_table('messages')
    op.drop_table('transcripts')
    op.drop_table('conversations')
    op.drop_table('recordings')
    op.drop_table('call_legs')
    op.drop_table('calls')
    op.drop_table('tenant_configs')
    op.drop_table('users')
    op.drop_table('tenants')